import { Config } from "effect"

function truthy(key: string): boolean {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

const TEAMCODE_EXPERIMENTAL = truthy("TEAMCODE_EXPERIMENTAL")
const experimental = TEAMCODE_EXPERIMENTAL
const copy = process.env["TEAMCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  TEAMCODE_AUTO_HEAP_SNAPSHOT: truthy("TEAMCODE_AUTO_HEAP_SNAPSHOT"),
  TEAMCODE_GIT_BASH_PATH: process.env["TEAMCODE_GIT_BASH_PATH"],
  TEAMCODE_CONFIG: process.env["TEAMCODE_CONFIG"],
  TEAMCODE_CONFIG_CONTENT: process.env["TEAMCODE_CONFIG_CONTENT"],
  TEAMCODE_DISABLE_AUTOUPDATE: truthy("TEAMCODE_DISABLE_AUTOUPDATE"),
  TEAMCODE_ALWAYS_NOTIFY_UPDATE: truthy("TEAMCODE_ALWAYS_NOTIFY_UPDATE"),
  TEAMCODE_DISABLE_PRUNE: truthy("TEAMCODE_DISABLE_PRUNE"),
  TEAMCODE_DISABLE_TERMINAL_TITLE: truthy("TEAMCODE_DISABLE_TERMINAL_TITLE"),
  TEAMCODE_SHOW_TTFD: truthy("TEAMCODE_SHOW_TTFD"),
  TEAMCODE_PERMISSION: process.env["TEAMCODE_PERMISSION"],
  TEAMCODE_DISABLE_AUTOCOMPACT: truthy("TEAMCODE_DISABLE_AUTOCOMPACT"),
  TEAMCODE_DISABLE_MODELS_FETCH: truthy("TEAMCODE_DISABLE_MODELS_FETCH"),
  TEAMCODE_DISABLE_MOUSE: truthy("TEAMCODE_DISABLE_MOUSE"),
  TEAMCODE_FAKE_VCS: process.env["TEAMCODE_FAKE_VCS"],
  TEAMCODE_SERVER_PASSWORD: process.env["TEAMCODE_SERVER_PASSWORD"],
  TEAMCODE_SERVER_USERNAME: process.env["TEAMCODE_SERVER_USERNAME"],

  // Experimental
  TEAMCODE_EXPERIMENTAL_FILEWATCHER: Config.boolean("TEAMCODE_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  TEAMCODE_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("TEAMCODE_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  TEAMCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("TEAMCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  TEAMCODE_MODELS_URL: process.env["TEAMCODE_MODELS_URL"],
  TEAMCODE_MODELS_PATH: process.env["TEAMCODE_MODELS_PATH"],
  TEAMCODE_DB: process.env["TEAMCODE_DB"],

  TEAMCODE_WORKSPACE_ID: process.env["TEAMCODE_WORKSPACE_ID"],
  TEAMCODE_EXPERIMENTAL_WORKSPACES: experimental || truthy("TEAMCODE_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get TEAMCODE_DISABLE_PROJECT_CONFIG() {
    return truthy("TEAMCODE_DISABLE_PROJECT_CONFIG")
  },
  get TEAMCODE_TUI_CONFIG() {
    return process.env["TEAMCODE_TUI_CONFIG"]
  },
  get TEAMCODE_CONFIG_DIR() {
    return process.env["TEAMCODE_CONFIG_DIR"]
  },
  get TEAMCODE_PURE() {
    return truthy("TEAMCODE_PURE")
  },
  get TEAMCODE_PLUGIN_META_FILE() {
    return process.env["TEAMCODE_PLUGIN_META_FILE"]
  },
  get TEAMCODE_CLIENT() {
    return process.env["TEAMCODE_CLIENT"] ?? "cli"
  },
}
